general.import = [
  "~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor]
style = { shape = "Beam", blinking = "Off" }

[selection]
save_to_clipboard = true

[colors.cursor] 
cursor = "0xf5e0dc"
text = "0x1e1e2e"

[colors.vi_mode_cursor]
cursor = "#b4befe"
text = "#1e1e2e"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.sdim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"
