local p = require("formoun.palette")

return {
  -- essential
  Normal = { fg = p.text, bg = p.base },
  NormalNC = { fg = p.text, bg = p.base },

  NormalFloat = { fg = p.text, bg = p.overlay0 },
  FloatBorder = { fg = p.text, bg = p.overlay0 },
  FloatTitle = { fg = p.text, bg = p.overlay0 },

  Cursor = { fg = p.text, bg = p.surface2 },
  CursorLine = { fg = "NONE", bg = p.surface0 },
  CursorColumn = { fg = p.text, bg = p.overlay0 },
  ColorColumn = { fg = p.text, bg = p.overlay0 },

  LineNr = { fg = p.muted, bg = "NONE" },
  CursorLineNr = { fg = p.text, bg = p.surface0 },
  LineNrAbove = { fg = p.muted, bg = "NONE" },
  LineNrBelow = { fg = p.muted, bg = "NONE" },

  Visual = { fg = "NONE", bg = p.surface1 },

  SignColumn = { fg = p.muted, bg = "NONE" },
  FoldColumn = { fg = p.muted, bg = p.overlay0 },
  Folded = { fg = p.muted, bg = p.overlay0 },

  StatusLine = { fg = p.text, bg = p.overlay0 },
  StatusLineNC = { fg = p.text, bg = p.overlay0 },
  TabLine = { fg = p.text, bg = p.overlay0 },
  TabLineSel = { fg = p.text, bg = p.overlay0 },
  TabLineFill = { fg = p.text, bg = p.overlay0 },
  WinSeparator = { fg = p.text, bg = p.overlay0 },
  VertSplit = { fg = p.text, bg = p.overlay0 },

  -- search/msg/inline
  Search = { fg = p.surface0, bg = p.aqua },
  IncSearch = { fg = p.surface0, bg = p.blue },
  CurSearch = { fg = p.surface0, bg = p.red },
  Substitute = { fg = p.text, bg = p.overlay0 },
  MatchParen = { fg = p.text },

  ModeMsg = { fg = p.text, bg = p.overlay0 },
  MoreMsg = { fg = p.text, bg = p.overlay0 },
  ErrorMsg = { fg = p.text, bg = p.overlay0 },
  WarningMsg = { fg = p.text, bg = p.overlay0 },
  MsgArea = { fg = p.text, bg = p.overlay0 },
  MsgSeparator = { fg = p.text, bg = p.overlay0 },
  Question = { fg = p.text, bg = p.overlay0 },

  NonText = { fg = p.text, bg = p.overlay0 },
  EndOfBuffer = { fg = p.muted, bg = "NONE" },
  Whitespace = { fg = p.text, bg = "NONE" },
  SpectialKey = { fg = p.text, bg = p.overlay0 },
  Conceal = { fg = p.text, bg = p.overlay0 },
  Directory = { fg = p.text, bg = p.overlay0 },

  -- legacy syntax
  Comment = { fg = p.muted },
  Constant = { fg = p.orange },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.orange },
  Boolean = { fg = p.orange },
  Float = { fg = p.orange },
  Identifier = { fg = p.text },
  Function = { fg = p.blue },
  Statement = { fg = p.red },
  Repeat = { fg = p.text },
  Label = { fg = p.text },
  Operator = { fg = p.sky },
  Keyword = { fg = p.red },
  Exception = { fg = p.text },
  PreProc = { fg = p.text },
  Include = { fg = p.text },
  Define = { fg = p.text },
  Macro = { fg = p.text },
  PreCondit = { fg = p.text },
  Type = { fg = p.yellow },
  StorageClass = { fg = p.yellow },
  Structure = { fg = p.yellow },
  Tag = { fg = p.text },
  Delimiter = { fg = p.text },
  Special = { fg = p.purple },
  SpecialChar = { fg = p.text },
  SpecialComment = { fg = p.text },
  Debug = { fg = p.text },
  Todo = { fg = p.text },
  Error = { fg = p.red },
  TooLong = { fg = p.text },

  LspReferenceText = {},
  LspReferenceRead = {},
  LspReferenceWrite = {},
  LspSignatureActiveParameter = {},
  LspCodeLens = {},
  LspCodeLensSeparator = {},
  LspInlayHint = {},

  -- blink.indent
  BlinkIndent = { fg = p.muted },
  BlinkIndentScope = {},
  BlinkIndentOrange = { fg = p.orange },
  BlinkIndentViolet = { fg = p.purple },
  BlinkIndentBlue = { fg = p.blue },
  BlinkIndentOrangeUnderline = {},
  BlinkIndentVioletUnderline = {},
  BlinkIndentBlueUnderline = {},
}
