[colors.normal]
black = "0x171717"
blue = "0x7c89e0"
cyan = "0x8adeff"
green = "0xadda71"
magenta = "0xc894eb"
red = "0xff5773"
white = "0xe3e3e3"
yellow = "0xffcb6b"

[colors.primary]
background = "0x171717"
foreground = "0xe3e3e3"

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode NerdFont"

[shell]
program = "/bin/fish"
